'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const model=()=>import('../src/ui/view-model.js');
test('Asset preview dimensions support widescreen, portrait and fallback without distortion',async()=>{const{aspect}=await model();assert.equal(aspect({width:2520,height:1080}),21/9);assert.equal(aspect({width:1080,height:1920}),9/16);assert.equal(aspect({ratio:'4:3'}),4/3);assert.equal(aspect({width:0,height:720}),16/9);assert.equal(aspect({ratio:'1:0'}),16/9);});
test('Browse category and search are independent of export scope',async()=>{const{filtered}=await model();const r={entries:[{kind:'video',name:'镜头',prompt:'一只狗',referenceTexts:[]}],assets:[{kind:'image',name:'人物参考'},{kind:'video',name:'视频结果'},{kind:'audio',name:'配音'}],options:{kinds:['video']}};assert.equal(filtered(r,'assets','image').length,1);assert.equal(filtered(r,'assets','video','结果').length,1);assert.equal(filtered(r,'prompts','all','一只狗').length,1);assert.deepEqual(r.options.kinds,['video']);});
test('Completed selection shows redownload; a partial or failed selection is not called complete',async()=>{const{downloadState}=await model();const assets=[{kind:'image',state:'done'},{kind:'video',state:'failed'},{kind:'audio',state:'pending'}];assert.equal(downloadState(assets,['image']).button,'重新下载');assert.equal(downloadState(assets,['image']).label,'下载完毕');assert.equal(downloadState(assets,['image','video']).complete,false);assert.equal(downloadState(assets,[]).complete,false);assert.equal(downloadState(assets,['image'],{active:true,paused:true}).label,'下载已暂停');});
test('Current media dimensions are preserved by platform normalizer',()=>{const{buildAssets}=require('../src/assets.cjs');const a=buildAssets({nodes:[{id:'v',type:'video',data:{source:'model_generated',resourceId:'new',title:'视频'}}],mediaResources:{new:{width:2520,height:1080,duration:5,urls:{download_url:'https://cdn.example.com/v.mp4',cover_url:'https://cdn.example.com/cover.jpg'}}}},'jimeng')[0];assert.equal(a.width,2520);assert.equal(a.height,1080);assert.equal(a.duration,5);assert.equal(a.previewUrl,'https://cdn.example.com/cover.jpg');});
test('Force redownload archives originals and actually fetches the selected file again',async t=>{
  const{normalize}=require('../src/normalize.cjs'),{ProjectStore}=require('../src/project-store.cjs'),{DownloadQueue}=require('../src/download-queue.cjs');
  const root=path.resolve(__dirname,'../validation');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'redownload-test-'));t.after(async()=>{if(path.dirname(dir)!==root||!path.basename(dir).startsWith('redownload-test-'))throw new Error('Unsafe cleanup');await fs.rm(dir,{recursive:true,force:true});});
  const r=normalize({nodes:[{id:'i',type:'image',data:{name:'人物',url:['https://cdn.example.com/i.png'],uploaded:true}}],edges:[],source:'fixture',frameUrl:'https://www.liblib.tv/detail/test'}, {platform:'liblib',author:'测试',title:'重新下载',inputUrl:'https://www.liblib.tv/detail/test'});
  const store=new ProjectStore(dir);await store.create(r);const a=r.assets[0],old=Buffer.from('old-file-data');await fs.writeFile(store.assetPath(a),old);Object.assign(a,{state:'done',bytes:old.length,total:old.length});await store.save(false);
  let calls=0;const png=Buffer.alloc(40);png.set([137,80,78,71,13,10,26,10]);const q=new DownloadQueue({fetcher:async()=>{calls++;return new Response(png,{headers:{'Content-Type':'image/png'}});},filePath:a=>store.assetPath(a),interval:0,onPrepare:async selected=>store.prepareRedownload(selected.map(a=>a.id)),onSettled:async()=>store.save(false)});
  await q.start(r.assets,['image']);assert.equal(calls,0);
  await q.start(r.assets,['image'],false,true);assert.equal(calls,1);assert.equal(a.state,'done');assert.deepEqual(await fs.readFile(store.assetPath(a)),png);const history=(await fs.readdir(store.directory)).find(n=>n.startsWith('历史素材_'));assert.ok(history);assert.deepEqual(await fs.readFile(path.join(store.directory,history)),old);
});
