'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {normalize,filterResult,markdown}=require('../src/normalize.cjs');
const {ProjectStore}=require('../src/project-store.cjs');
const {DownloadQueue}=require('../src/download-queue.cjs');
const {promptKinds}=require('../src/prompt-types.cjs');
const meta={platform:'liblib',author:'作者',title:'同一项目',inputUrl:'https://www.liblib.tv/detail/v07',canvasUrl:'https://www.liblib.tv/detail/v07'};
function result(){return normalize({nodes:[
  ...['text_to_image','image_to_image','unknown'].map((mode,i)=>({id:'image'+i,type:'image',data:{action:'image_generate',name:'图'+i,url:['https://cdn.example.com/'+i+'.png'],params:{prompt:'图片正文'+i,modeType:mode}}})),
  {id:'uploaded',type:'image',data:{uploaded:true,name:'上传参考',url:['https://cdn.example.com/upload.png']}},
  {id:'v',type:'video',data:{action:'video_generate',params:{prompt:'视频正文'}}},
  {id:'a',type:'audio',data:{action:'audio_generate',params:{prompt:'音频正文'}}},
  {id:'t',type:'text',data:{content:'独立文本正文'}}],edges:[],source:'fixture',frameUrl:meta.canvasUrl},meta);}
async function temp(t){const root=path.resolve(__dirname,'../validation');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'v07-test-'));t.after(async()=>{assert.equal(path.dirname(dir),root);assert.match(path.basename(dir),/^v07-test-/);await fs.rm(dir,{recursive:true,force:true});});return dir;}
test('One image category includes all image modes while preserving prompts and parameters',async()=>{const r=result(),image=filterResult(r,['image']);assert.equal(image.entries.length,3);assert.ok(image.entries.every(e=>e.kind.startsWith('image_')));const doc=markdown(image);assert.equal(doc.split('## 图片提示词').length-1,1);for(let i=0;i<3;i++)assert.ok(doc.includes('图片正文'+i));assert.ok(!doc.includes('## 文生图'));const {filtered,countKinds}=await import('../src/ui/view-model.js');assert.equal(filtered(r,'prompts',new Set(['image'])).length,3);assert.equal(countKinds(r.entries,['image']).image,3);assert.deepEqual(promptKinds(['image_text','image_reference','image_unknown']),['image']);});
test('Download-first creates one folder and writes no Markdown; later saves share that folder',async t=>{const root=await temp(t),r=result(),store=new ProjectStore(root);await store.create(r,{kinds:['image'],split:true,mode:'full'},false);const directory=store.directory;assert.equal((await fs.readdir(directory)).filter(n=>n.endsWith('.md')).length,0);const png=Buffer.alloc(48);png.set([137,80,78,71,13,10,26,10]);let requests=0;const queue=new DownloadQueue({fetcher:async()=>{requests++;return new Response(png,{headers:{'content-type':'image/png'}});},interval:0,filePath:a=>store.assetPath(a),onSettled:()=>store.checkpoint()});await queue.start(r.assets,['image']);assert.equal(requests,4);assert.equal((await fs.readdir(directory)).filter(n=>n.endsWith('.md')).length,0);await store.save(true);assert.equal(store.directory,directory);assert.equal(store.documents.length,1);assert.ok(store.documents[0].endsWith('__图片提示词.md'));store.options={...store.options,kinds:['video','image','audio','text'],split:false};await store.save(true);assert.equal(store.directory,directory);assert.equal(store.documents.length,1);assert.equal((await fs.readdir(root)).filter(n=>n!==' .项目索引.json'&&!n.startsWith('.')).length,1);});
test('Stopping between category files retains completed files and leaves later files unwritten',async t=>{const store=new ProjectStore(await temp(t));await store.create(result(),{split:true},false);const token={cancelled:false},original=store.archive.bind(store);let archived=0;await store.save();for(const name of store.documents)await fs.writeFile(path.join(store.directory,name),'previous content');store.archive=async name=>{await original(name);if(++archived===1)token.cancelled=true;};const saved=await store.save(true,token);assert.equal(saved.cancelled,true);assert.equal(saved.savedDocuments.length,1);assert.ok((await fs.readFile(path.join(store.directory,saved.savedDocuments[0]),'utf8')).includes('视频正文'));for(const name of store.documents.slice(1))assert.equal(await fs.readFile(path.join(store.directory,name),'utf8'),'previous content');});
test('Progress is file-count based; failed files never make the bar complete',async()=>{const {downloadMetrics}=await import('../src/ui/view-model.js');const assets=Array.from({length:100},(_,i)=>({id:String(i),kind:'image',state:i===0?'done':i===1?'failed':'pending'}));const m=downloadMetrics(assets,'image',{active:true,speeds:{image:2048}});assert.equal(m.percent,1);assert.equal(m.failed,1);assert.equal(m.speed,2048);const fresh=downloadMetrics(assets,'image',{files:[{id:'2',state:'done'}]});assert.equal(fresh.done,2);assert.equal(fresh.percent,2);assert.equal(fresh.speed,0);});
