let openMediaPreview=()=>{},closeMediaPreview=()=>{},activePreviewAnchor=null;
export function imageRect(image){const r=image.getBoundingClientRect(),ratio=image.naturalWidth/image.naturalHeight;if(!ratio)return r;const w=Math.min(r.width,r.height*ratio),h=w/ratio;return{left:r.left+(r.width-w)/2,top:r.top+(r.height-h)/2,width:w,height:h,right:r.left+(r.width+w)/2,bottom:r.top+(r.height+h)/2};}
export function conditionalTitle(node){const update=()=>{if(!node.isConnected)return;const clipped=node.scrollWidth>node.clientWidth+1||[...node.children].some(c=>c.scrollWidth>c.clientWidth+1);if(clipped)node.title=node.textContent;else node.removeAttribute('title');};node.addEventListener('mouseenter',update);node.addEventListener('focus',update);}
export function bindSmallPreview(container,image,asset,context){
  const preview=document.getElementById('hover-preview');let timer,inside=false;
  const show=()=>{if(!inside||!image?.naturalWidth)return;const shown=imageRect(image),w=Math.min(460,innerWidth-32),h=Math.min(300,innerHeight-80),ratio=image.naturalWidth/image.naturalHeight,pw=Math.min(w-16,h*ratio),ph=pw/ratio;if(pw<=shown.width*1.12||ph<=shown.height*1.12){preview.hidden=true;return;}const anchor=container.getBoundingClientRect(),width=pw+16,height=ph+43,gap=12;let x=anchor.right+gap;if(x+width>innerWidth-12)x=anchor.left-width-gap;if(x<12)x=Math.max(12,Math.min(innerWidth-width-12,anchor.left));const y=Math.max(12,Math.min(innerHeight-height-12,anchor.top));preview.style.width=width+'px';preview.querySelector('img').style.height=ph+'px';preview.querySelector('img').src=image.currentSrc||image.src;preview.querySelector('div').textContent=asset.name;preview.style.left=x+'px';preview.style.top=y+'px';preview.hidden=false;activePreviewAnchor=container;};
  container.addEventListener('mouseenter',()=>{inside=true;clearTimeout(timer);timer=setTimeout(async()=>{if(!inside)return;if(!image?.naturalWidth)await image?.requestFrame?.();show();},280);});image?.addEventListener('load',show);container.addEventListener('mouseleave',()=>{inside=false;clearTimeout(timer);if(activePreviewAnchor===container)preview.hidden=true;});container.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();preview.hidden=true;openMediaPreview(asset,context);});
  if(container.classList.contains('cover')){const button=document.createElement('button');button.type='button';button.className='preview-media';button.textContent='预览';button.setAttribute('aria-label','预览 '+asset.name);button.addEventListener('click',e=>{e.stopPropagation();preview.hidden=true;openMediaPreview(asset,context);});container.append(button);}
}
export function bindMagnifier(stage,image,asset,context){
  const toggle=document.createElement('button');toggle.type='button';toggle.textContent='放大镜';toggle.className='magnify';toggle.setAttribute('aria-pressed','false');const lens=document.createElement('div');lens.className='magnifier-lens';lens.hidden=true;stage.append(toggle,lens);let enabled=false;
  toggle.addEventListener('click',e=>{e.stopPropagation();enabled=!enabled;toggle.classList.toggle('active',enabled);toggle.setAttribute('aria-pressed',String(enabled));lens.hidden=true;stage.classList.toggle('magnifying',enabled);toggle.title=enabled?'移动鼠标查看局部；当前清晰度取决于已加载图片':'开启局部放大';});
  stage.addEventListener('pointermove',e=>{if(!enabled||!image.naturalWidth||e.target.closest('button')){lens.hidden=true;return;}const r=imageRect(image),p=stage.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x<0||y<0||x>r.width||y>r.height){lens.hidden=true;return;}const size=Math.min(190,p.width*.42,p.height*.7),zoom=2;lens.style.width=lens.style.height=size+'px';lens.style.left=Math.max(0,Math.min(p.width-size,e.clientX-p.left-size/2))+'px';lens.style.top=Math.max(0,Math.min(p.height-size,e.clientY-p.top-size/2))+'px';lens.style.backgroundImage=`url("${image.currentSrc||image.src}")`;lens.style.backgroundSize=`${r.width*zoom}px ${r.height*zoom}px`;lens.style.backgroundPosition=`${size/2-x*zoom}px ${size/2-y*zoom}px`;lens.hidden=false;});stage.addEventListener('pointerleave',()=>{lens.hidden=true;});stage.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();openMediaPreview(asset,context);});image.addEventListener('click',e=>{if(enabled)e.stopImmediatePropagation();},true);
}
export function initMediaDialog(createMedia,stop,enterReader){
  const dialog=document.getElementById('media-dialog'),body=document.getElementById('media-dialog-body');let current=null;
  closeMediaPreview=()=>{current=null;if(dialog.open)dialog.close();else{stop(body);body.replaceChildren();}};
  openMediaPreview=(asset,context)=>{current={asset,context};document.getElementById('hover-preview').hidden=true;for(const p of document.querySelectorAll('video,audio'))p.pause();stop(body);body.replaceChildren(createMedia(asset,context));document.getElementById('media-dialog-title').textContent=asset.name;dialog.showModal();if(asset.kind!=='image')body.querySelector('.load-media')?.click();};
  document.getElementById('media-dialog-reader').addEventListener('click',()=>{if(!current)return;const{asset,context}=current;closeMediaPreview();enterReader(asset,context);});
  dialog.addEventListener('close',()=>{current=null;stop(body);body.replaceChildren();});document.getElementById('media-dialog-close').addEventListener('click',closeMediaPreview);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeMediaPreview();}});for(const event of ['scroll','resize'])window.addEventListener(event,()=>{document.getElementById('hover-preview').hidden=true;},true);
}

// Click scrolls one step; a held primary pointer scrolls continuously until released.
export function bindScrollArrow(button,viewport,direction){
  let delay,frame,last=0,held=false,pointerDown=false;
  const stop=()=>{clearTimeout(delay);cancelAnimationFrame(frame);last=0;window.removeEventListener('blur',release);};
  const tick=now=>{if(!button.isConnected||button.disabled||!pointerDown){stop();return;}if(last)viewport.scrollLeft+=direction*Math.min(40,now-last)*1.2;last=now;frame=requestAnimationFrame(tick);};
  button.addEventListener('pointerdown',e=>{if(e.button!==0||button.disabled)return;stop();held=false;pointerDown=true;window.addEventListener('blur',release);button.setPointerCapture(e.pointerId);delay=setTimeout(()=>{held=true;frame=requestAnimationFrame(tick);},300);});
  const release=()=>{pointerDown=false;stop();};
  button.addEventListener('pointerup',release);button.addEventListener('pointercancel',()=>{held=true;release();});button.addEventListener('lostpointercapture',release);
  button.addEventListener('click',()=>{if(!held)viewport.scrollBy({left:direction*Math.max(160,viewport.clientWidth*.65),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});held=false;});
  return release;
}
