'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {inspectAccount}=require('./account-state.cjs');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
module.exports=async({ui,root,send,setResult,setFetcher,getStore})=>{
  const run=code=>ui.webContents.executeJavaScript(code),checks=[],errors=[];ui.webContents.on('console-message',e=>{if(e.level==='error'||e.level===3)errors.push(e.message);});
  const until=async(code)=>{for(let i=0;i<200;i++){const r=await run(code);if(r)return r;await wait(50);}throw new Error('Timed out: '+code+' '+JSON.stringify(await run("({notice:document.getElementById('saved').textContent,status:document.getElementById('status').textContent,saveDisabled:document.getElementById('save-prompts').disabled})")));};
  const check=s=>{checks.push(s);console.log('PASS '+s);};
  const shot=async name=>{await run('scrollTo(0,0)');await wait(160);await fs.writeFile(path.join(root,'validation',name+'.png'),(await ui.webContents.capturePage()).toPNG());};
  await until("document.querySelectorAll('#export-types input').length===4");
  await run("document.querySelector('[data-appearance-mode=light]').click()");
  assert.equal(await run("document.querySelectorAll('.account-dot').length"),0);
  assert.deepEqual(await run("[...document.querySelectorAll('#export-types label')].map(e=>e.childNodes[1].textContent)"),['视频提示词','图片提示词','音频提示词','独立文本']);check('Four prompt categories and account indicators removed');
  const source=JSON.parse(await fs.readFile(path.join(root,'validation/liblib-snapshot.json'),'utf8')),r=structuredClone(source);r.metadata.title='胡来万事屋 · v1.0 验证 '+crypto.randomBytes(3).toString('hex');r.metadata.canvasUrl='https://www.liblib.tv/detail/v08-'+crypto.randomBytes(6).toString('hex');
  const representative=['video','image','audio'].map(k=>r.assets.find(a=>a.kind===k&&a.url)).filter(Boolean);assert.equal(representative.length,3);r.assets=representative.flatMap(a=>[0,1].map(i=>({...a,id:crypto.randomBytes(12).toString('hex'),fileName:a.fileName.replace(/(\.[^.]+)$/,'_v08_'+i+'$1'),state:'pending',bytes:0,total:0,savedBytes:0,previewUrl:'',name:a.name+' '+(i+1)})));
  const large=JSON.parse(await fs.readFile(path.join(root,'validation/liblib-large-snapshot.json'),'utf8'));r.entries.push(...['image_text','image_reference'].map(k=>structuredClone(large.entries.find(e=>e.kind===k))));
  // Use known local media bytes only as transport fixtures. No real CDN requests.
  const fixtureRoot=path.resolve(root,'../升级版_v0.5/validation/projects/liblib_蓝喵_胡来万事屋'),data=new Map();for(const a of representative)data.set(a.url,await fs.readFile(path.join(fixtureRoot,a.fileName)));
  let originalRequests=[];setFetcher((url,opts)=>{const buffer=data.get(url);if(!buffer)return Promise.resolve(new Response('',{status:404}));const asset=r.assets.find(a=>a.url===url);if(opts.headers?.Range)return Promise.resolve(new Response('',{status:404}));originalRequests.push(asset.kind);let offset=0;return Promise.resolve(new Response(new ReadableStream({async pull(c){await wait(180);try{if(offset>=buffer.length){c.close();return;}const end=Math.min(buffer.length,offset+Math.max(32,Math.ceil(buffer.length/5)));c.enqueue(buffer.subarray(offset,end));offset=end;}catch{}},cancel(){offset=buffer.length;}}),{headers:{'content-type':asset.kind==='audio'?'audio/mpeg':asset.kind==='image'?'image/png':'video/mp4','content-length':String(buffer.length)}}));});
  setResult(r);await run("document.getElementById('url').value='https://www.liblib.tv/detail/v08';document.getElementById('start').click()");await until("document.getElementById('start').textContent==='停止读取'");await until("document.getElementById('start').textContent==='开始读取画布'&&document.getElementById('prompt-total').textContent!=='0'");assert.equal(getStore().directory,null);assert.ok(!await run("document.getElementById('status').textContent.includes('自动保存')"));check('Actual read IPC produces results without a project folder or Markdown');
  await run("document.getElementById('mode-toggle').click()");await until("document.getElementById('mode-label').textContent==='轻量模式'");assert.equal(getStore().directory,null);
  await run("document.getElementById('mode-toggle').click()");await until("document.getElementById('mode-label').textContent==='全能模式'");assert.equal(await run("document.getElementById('mode-toggle').textContent"),'轻量模式');assert.equal(getStore().directory,null);check('Both mode switches do not save prompts');
  await run("for(const c of document.querySelectorAll('#download-types input')){c.checked=c.dataset.kind==='image';c.dispatchEvent(new Event('change'));}document.getElementById('download').click()");await until("document.getElementById('download').textContent==='停止下载'");await until("document.querySelector('.download-row[data-kind=image] .download-count').textContent.startsWith('1 /')");await shot('V08-下载进行中');await run("document.getElementById('download').click()");await until("document.getElementById('download').textContent==='开始下载'");const directory=getStore().directory;assert.ok(directory);assert.equal((await fs.readdir(directory)).filter(n=>n.endsWith('.md')).length,0);assert.ok(originalRequests.every(k=>k==='image'));assert.ok(getStore().result.assets.some(a=>a.kind==='image'&&a.state==='done'));assert.ok(getStore().result.assets.filter(a=>a.kind!=='image').every(a=>a.state==='pending'));check('Checkbox download, stop button, retained files and no implicit prompt save');
  await run("document.getElementById('split').checked=true;for(const c of document.querySelectorAll('#export-types input'))c.checked=c.dataset.kind==='image';document.getElementById('save-prompts').click()");await until("document.getElementById('saved').textContent.startsWith('已保存：')");assert.equal(getStore().directory,directory);assert.equal(getStore().documents.length,1);assert.ok(getStore().documents[0].endsWith('__图片提示词.md'));const doc=await fs.readFile(path.join(directory,getStore().documents[0]),'utf8');assert.ok(doc.includes('## 图片提示词'));assert.ok(!doc.includes('## 文生图'));check('Explicit category save uses the download folder');
  const before=await fs.readFile(path.join(directory,getStore().documents[0]),'utf8');await run("document.getElementById('split').click();for(const c of document.querySelectorAll('#export-types input')){c.checked=true;c.dispatchEvent(new Event('change'));}");await wait(800);assert.equal(await fs.readFile(path.join(directory,getStore().documents[0]),'utf8'),before);assert.equal(getStore().documents.length,1);check('Editing save selections does not write Markdown');
  await run("document.getElementById('save-prompts').click()");await until("!document.getElementById('save-prompts').disabled&&document.getElementById('save-prompts').textContent==='保存提示词'");await until("document.getElementById('saved').textContent.startsWith('已保存：')");assert.equal(getStore().directory,directory);assert.equal(getStore().documents.length,1);assert.ok(!getStore().documents[0].includes('__'));check('Merged save shares the project folder');
  const geometry=await run("(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,right:r.right,width:r.width,height:r.height};};return{track:rect('.progress-track'),row:rect('.download-row'),save:rect('#save-prompts'),download:rect('#download'),start:rect('#start'),title:getComputedStyle(document.querySelector('h1')).fontSize,project:getComputedStyle(document.getElementById('project-name')).fontSize,overflow:document.documentElement.scrollWidth>innerWidth+1};})()");assert.equal(geometry.track.height,16);assert.ok(geometry.track.width>geometry.row.width*.55);assert.equal(geometry.start.right,geometry.save.right);assert.equal(geometry.save.right,geometry.download.right);assert.equal(geometry.title,geometry.project);assert.equal(geometry.overflow,false);check('16px rounded progress tracks and aligned primary action column');
  await shot('V08-全能模式');await run("document.querySelector('[data-appearance-mode=dark]').click()");await shot('V08-深色模式');await run("document.querySelector('[data-appearance-mode=light]').click()");
  for(const width of [800,680]){ui.setSize(width,940);await wait(250);assert.ok(await run('document.documentElement.scrollWidth<=innerWidth+1'));const bounds=await run("[...document.querySelectorAll('.progress-track')].map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}))");assert.ok(bounds.every(e=>e.width>100&&e.height===16));await shot('V08-'+width+'窗口');}check('Narrow windows retain visible progress bars without horizontal overflow');ui.setSize(1440,960);
  await require('./verify-v08-layout.cjs')({ui,root,send});check('v1.0 module layout verified at six widths');
  // Verify account evidence independently of any work metadata.
  const accountCases=await run(`(()=>{const saved=document.body.innerHTML;const inspect=${inspectAccount.toString()};const wrap=html=>{document.body.innerHTML=html;return inspect();};const unknown=wrap('<main><h1>作品可以访问</h1><span>作者 176****1770</span></main>');const loggedOut=wrap('<button>登录</button><h1>公开作品</h1>');const loggedIn=wrap('<div style="position:fixed;right:20px;top:20px;width:260px"><strong>176****1770</strong><span>UUID | Access key</span></div>');document.body.innerHTML=saved;return{unknown,loggedOut,loggedIn};})()`);assert.equal(accountCases.unknown.state,'unknown');assert.equal(accountCases.loggedOut.state,'logged-out');assert.equal(accountCases.loggedIn.state,'logged-in');assert.equal(accountCases.loggedIn.username,'176****1770');check('Public work and author details do not imply account login');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'validation/v08-workflow-report.json'),JSON.stringify({passed:true,checks,geometry,errors,transport:'Known v0.5 local media bytes; no platform CDN availability claim'},null,2));
};
